"""empty message

Revision ID: 20390a08f8a2
Revises: 13cc2e7c68e4
Create Date: 2020-02-29 13:25:59.021823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20390a08f8a2'
down_revision = '13cc2e7c68e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
